
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/Compiler/CLion/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "D:/Compiler/CLion/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/Compiler/CLion/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/Compiler/CLion/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      用于 .NET Framework 的 Microsoft (R) 生成引擎版本 17.2.1+52cd2da31
      版权所有(C) Microsoft Corporation。保留所有权利。
      
      生成启动时间为 2025/6/19 13:07:13。
      节点 1 上的项目“E:\\Desktop\\RE笔记\\REDemo\\cmake-build-debug-mingw\\CMakeFiles\\3.27.8\\CompilerIdC\\CompilerIdC.vcxproj”(默认目标)。
      PrepareForBuild:
        正在创建目录“Debug\\”。
        正在创建目录“Debug\\CompilerIdC.tlog\\”。
      InitializeBuildStatus:
        正在创建“Debug\\CompilerIdC.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
      ClCompile:
        D:\\Compiler\\VisualStudio\\Visual Studio IDE\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        D:\\Compiler\\VisualStudio\\Visual Studio IDE\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> E:\\Desktop\\RE笔记\\REDemo\\cmake-build-debug-mingw\\CMakeFiles\\3.27.8\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=D:\\Compiler\\VisualStudio\\Visual Studio IDE\\VC\\Tools\\MSVC\\14.32.31326\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        正在删除文件“Debug\\CompilerIdC.tlog\\unsuccessfulbuild”。
        正在对“Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate”执行 Touch 任务。
      已完成生成项目“E:\\Desktop\\RE笔记\\REDemo\\cmake-build-debug-mingw\\CMakeFiles\\3.27.8\\CompilerIdC\\CompilerIdC.vcxproj”(默认目标)的操作。
      
      已成功生成。
          0 个警告
          0 个错误
      
      已用时间 00:00:08.15
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        E:/Desktop/RE笔记/REDemo/cmake-build-debug-mingw/CMakeFiles/3.27.8/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/Compiler/CLion/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/Compiler/CLion/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/Compiler/CLion/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      用于 .NET Framework 的 Microsoft (R) 生成引擎版本 17.2.1+52cd2da31
      版权所有(C) Microsoft Corporation。保留所有权利。
      
      生成启动时间为 2025/6/19 13:07:22。
      节点 1 上的项目“E:\\Desktop\\RE笔记\\REDemo\\cmake-build-debug-mingw\\CMakeFiles\\3.27.8\\CompilerIdCXX\\CompilerIdCXX.vcxproj”(默认目标)。
      PrepareForBuild:
        正在创建目录“Debug\\”。
        正在创建目录“Debug\\CompilerIdCXX.tlog\\”。
      InitializeBuildStatus:
        正在创建“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
      ClCompile:
        D:\\Compiler\\VisualStudio\\Visual Studio IDE\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        D:\\Compiler\\VisualStudio\\Visual Studio IDE\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> E:\\Desktop\\RE笔记\\REDemo\\cmake-build-debug-mingw\\CMakeFiles\\3.27.8\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=D:\\Compiler\\VisualStudio\\Visual Studio IDE\\VC\\Tools\\MSVC\\14.32.31326\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        正在删除文件“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”。
        正在对“Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate”执行 Touch 任务。
      已完成生成项目“E:\\Desktop\\RE笔记\\REDemo\\cmake-build-debug-mingw\\CMakeFiles\\3.27.8\\CompilerIdCXX\\CompilerIdCXX.vcxproj”(默认目标)的操作。
      
      已成功生成。
          0 个警告
          0 个错误
      
      已用时间 00:00:01.71
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        E:/Desktop/RE笔记/REDemo/cmake-build-debug-mingw/CMakeFiles/3.27.8/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/Compiler/CLion/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "D:/Compiler/CLion/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "E:/Desktop/RE\u7b14\u8bb0/REDemo/cmake-build-debug-mingw/CMakeFiles/CMakeScratch/TryCompile-cnr0c2"
      binary: "E:/Desktop/RE\u7b14\u8bb0/REDemo/cmake-build-debug-mingw/CMakeFiles/CMakeScratch/TryCompile-cnr0c2"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'E:/Desktop/RE笔记/REDemo/cmake-build-debug-mingw/CMakeFiles/CMakeScratch/TryCompile-cnr0c2'
        
        Run Build Command(s): "D:/Compiler/VisualStudio/Visual Studio IDE/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_e03c3.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        用于 .NET Framework 的 Microsoft (R) 生成引擎版本 17.2.1+52cd2da31
        版权所有(C) Microsoft Corporation。保留所有权利。
        
        生成启动时间为 2025/6/19 13:07:24。
        节点 1 上的项目“E:\\Desktop\\RE笔记\\REDemo\\cmake-build-debug-mingw\\CMakeFiles\\CMakeScratch\\TryCompile-cnr0c2\\cmTC_e03c3.vcxproj”(默认目标)。
        PrepareForBuild:
          正在创建目录“cmTC_e03c3.dir\\Debug\\”。
          正在创建目录“E:\\Desktop\\RE笔记\\REDemo\\cmake-build-debug-mingw\\CMakeFiles\\CMakeScratch\\TryCompile-cnr0c2\\Debug\\”。
          正在创建目录“cmTC_e03c3.dir\\Debug\\cmTC_e03c3.tlog\\”。
        InitializeBuildStatus:
          正在创建“cmTC_e03c3.dir\\Debug\\cmTC_e03c3.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
        ClCompile:
          D:\\Compiler\\VisualStudio\\Visual Studio IDE\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_e03c3.dir\\Debug\\\\" /Fd"cmTC_e03c3.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "D:\\Compiler\\CLion\\CLion 2023.3.4\\bin\\cmake\\win\\x64\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
          用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.32.31332 版
          CMakeCCompilerABI.c
          版权所有(C) Microsoft Corporation。保留所有权利。
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_e03c3.dir\\Debug\\\\" /Fd"cmTC_e03c3.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "D:\\Compiler\\CLion\\CLion 2023.3.4\\bin\\cmake\\win\\x64\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
        Link:
          D:\\Compiler\\VisualStudio\\Visual Studio IDE\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"E:\\Desktop\\RE笔记\\REDemo\\cmake-build-debug-mingw\\CMakeFiles\\CMakeScratch\\TryCompile-cnr0c2\\Debug\\cmTC_e03c3.exe" /INCREMENTAL /ILK:"cmTC_e03c3.dir\\Debug\\cmTC_e03c3.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"E:/Desktop/RE笔记/REDemo/cmake-build-debug-mingw/CMakeFiles/CMakeScratch/TryCompile-cnr0c2/Debug/cmTC_e03c3.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"E:/Desktop/RE笔记/REDemo/cmake-build-debug-mingw/CMakeFiles/CMakeScratch/TryCompile-cnr0c2/Debug/cmTC_e03c3.lib" /MACHINE:X64  /machine:x64 cmTC_e03c3.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_e03c3.vcxproj -> E:\\Desktop\\RE笔记\\REDemo\\cmake-build-debug-mingw\\CMakeFiles\\CMakeScratch\\TryCompile-cnr0c2\\Debug\\cmTC_e03c3.exe
        FinalizeBuildStatus:
          正在删除文件“cmTC_e03c3.dir\\Debug\\cmTC_e03c3.tlog\\unsuccessfulbuild”。
          正在对“cmTC_e03c3.dir\\Debug\\cmTC_e03c3.tlog\\cmTC_e03c3.lastbuildstate”执行 Touch 任务。
        已完成生成项目“E:\\Desktop\\RE笔记\\REDemo\\cmake-build-debug-mingw\\CMakeFiles\\CMakeScratch\\TryCompile-cnr0c2\\cmTC_e03c3.vcxproj”(默认目标)的操作。
        
        已成功生成。
            0 个警告
            0 个错误
        
        已用时间 00:00:01.60
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/Compiler/CLion/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "D:/Compiler/CLion/CLion 2023.3.4/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "E:/Desktop/RE\u7b14\u8bb0/REDemo/cmake-build-debug-mingw/CMakeFiles/CMakeScratch/TryCompile-bexhja"
      binary: "E:/Desktop/RE\u7b14\u8bb0/REDemo/cmake-build-debug-mingw/CMakeFiles/CMakeScratch/TryCompile-bexhja"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'E:/Desktop/RE笔记/REDemo/cmake-build-debug-mingw/CMakeFiles/CMakeScratch/TryCompile-bexhja'
        
        Run Build Command(s): "D:/Compiler/VisualStudio/Visual Studio IDE/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_72eeb.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        用于 .NET Framework 的 Microsoft (R) 生成引擎版本 17.2.1+52cd2da31
        版权所有(C) Microsoft Corporation。保留所有权利。
        
        生成启动时间为 2025/6/19 13:07:26。
        节点 1 上的项目“E:\\Desktop\\RE笔记\\REDemo\\cmake-build-debug-mingw\\CMakeFiles\\CMakeScratch\\TryCompile-bexhja\\cmTC_72eeb.vcxproj”(默认目标)。
        PrepareForBuild:
          正在创建目录“cmTC_72eeb.dir\\Debug\\”。
          正在创建目录“E:\\Desktop\\RE笔记\\REDemo\\cmake-build-debug-mingw\\CMakeFiles\\CMakeScratch\\TryCompile-bexhja\\Debug\\”。
          正在创建目录“cmTC_72eeb.dir\\Debug\\cmTC_72eeb.tlog\\”。
        InitializeBuildStatus:
          正在创建“cmTC_72eeb.dir\\Debug\\cmTC_72eeb.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
        ClCompile:
          D:\\Compiler\\VisualStudio\\Visual Studio IDE\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_72eeb.dir\\Debug\\\\" /Fd"cmTC_72eeb.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "D:\\Compiler\\CLion\\CLion 2023.3.4\\bin\\cmake\\win\\x64\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
          用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.32.31332 版
          CMakeCXXCompilerABI.cpp
          版权所有(C) Microsoft Corporation。保留所有权利。
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_72eeb.dir\\Debug\\\\" /Fd"cmTC_72eeb.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "D:\\Compiler\\CLion\\CLion 2023.3.4\\bin\\cmake\\win\\x64\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          D:\\Compiler\\VisualStudio\\Visual Studio IDE\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"E:\\Desktop\\RE笔记\\REDemo\\cmake-build-debug-mingw\\CMakeFiles\\CMakeScratch\\TryCompile-bexhja\\Debug\\cmTC_72eeb.exe" /INCREMENTAL /ILK:"cmTC_72eeb.dir\\Debug\\cmTC_72eeb.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"E:/Desktop/RE笔记/REDemo/cmake-build-debug-mingw/CMakeFiles/CMakeScratch/TryCompile-bexhja/Debug/cmTC_72eeb.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"E:/Desktop/RE笔记/REDemo/cmake-build-debug-mingw/CMakeFiles/CMakeScratch/TryCompile-bexhja/Debug/cmTC_72eeb.lib" /MACHINE:X64  /machine:x64 cmTC_72eeb.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_72eeb.vcxproj -> E:\\Desktop\\RE笔记\\REDemo\\cmake-build-debug-mingw\\CMakeFiles\\CMakeScratch\\TryCompile-bexhja\\Debug\\cmTC_72eeb.exe
        FinalizeBuildStatus:
          正在删除文件“cmTC_72eeb.dir\\Debug\\cmTC_72eeb.tlog\\unsuccessfulbuild”。
          正在对“cmTC_72eeb.dir\\Debug\\cmTC_72eeb.tlog\\cmTC_72eeb.lastbuildstate”执行 Touch 任务。
        已完成生成项目“E:\\Desktop\\RE笔记\\REDemo\\cmake-build-debug-mingw\\CMakeFiles\\CMakeScratch\\TryCompile-bexhja\\cmTC_72eeb.vcxproj”(默认目标)的操作。
        
        已成功生成。
            0 个警告
            0 个错误
        
        已用时间 00:00:01.40
        
      exitCode: 0
...
